export const LOAD_YOUTUBE_VIDEOS = 'LOAD_YOUTUBE_VIDEOS';
export const ENABLE_PRELOADER = 'ENABLE_PRELOADER';
export const DISABLE_PRELOADER = 'DISABLE_PRELOADER';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
